version: '3.1'

services:
 
  ams_backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/ams_backend
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
