version: '3.1'

services:
  ams_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ams_backend
    networks:
     - ams_network

  ams_backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
     - ams_db
    networks:
     - ams_network

networks:
  ams_network:
    driver: bridge