version: '3.1'

services:
  ams_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ams_backend
    network_mode: "host"

  ams_backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    network_mode: "host"
    depends_on:
     - ams_db
