version: '3.1'

services:
  ams_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ams_backend
    ports:
      - "3306:3306"
    networks:
      - my-network

  ams_backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:9090"
    depends_on:
      - ams_db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
